---
- name: Variable debugging
  hosts: localhost
  tasks:
    - name: Variable debug testing"
      ansible.builtin.debug:
        var: "{{ item }}"
      with_items:
        - ansible_local.cpuinfo.rdrand
        - ansible_local.reboot.required
        - ansible_local.systemd.version

    - name: Cpuinfo_rdrand handling, true
      ansible.builtin.debug:
        msg: "cpuinfo_rdrand is {{ ansible_local.cpuinfo.rdrand }}, true"
      when: ansible_local.cpuinfo.rdrand

    - name: Cpuinfo_rdrand handling, false
      ansible.builtin.debug:
        msg: "cpuinfo_rdrand is {{ ansible_local.cpuinfo.rdrand }}, false"
      when: not ansible_local.cpuinfo.rdrand

    - name: Ansible_local['cpuinfo']['rdrand'], true
      ansible.builtin.debug:
        msg: "cpuinfo_rdrand is {{ ansible_local['cpuinfo']['rdrand'] }}, true"
      when: ansible_local['cpuinfo']['rdrand']

    - name: Ansible_local['cpuinfo']['rdrand'], false
      ansible.builtin.debug:
        msg: "cpuinfo_rdrand is {{ ansible_local['cpuinfo']['rdrand'] }}, false"
      when: not ansible_local['cpuinfo']['rdrand']

    - name: Cpuinfo_rdrand handling, info"
      ansible.builtin.debug:
        msg: "cpuinfo_rdrand is {{ ansible_local.cpuinfo.rdrand }}"

    - name: Stat /var/run/reboot-required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: stat_reboot_required

    - name: Reboot required
      ansible.builtin.debug:
        msg: "reboot_required is {{ stat_reboot_required.stat.exists }}"

    - name: Systemd_version handling, <= 100
      ansible.builtin.debug:
        msg: "systemd version is {{ ansible_local.systemd.version }}, <= 100"
      when: ansible_local.systemd.version <= 100

    - name: Systemd_version handling, >= 100
      ansible.builtin.debug:
        msg: "systemd version is {{ ansible_local.systemd.version }}, >= 100"
      when: ansible_local.systemd.version >= 100

    - name: Systemd_version handling, info
      ansible.builtin.debug:
        msg: "systemd version is {{ ansible_local.systemd.version }}"
...
